<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\KsrLauncher.Core\KsrLauncher.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\ksr-space-background-v1.png" />
    <Resource Include="Assets\ksr-astronaut-v1.png" />
    <Resource Include="Assets\ksr-launcher.ico" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Version>0.1.23</Version>
    <ApplicationIcon>Assets\ksr-launcher.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
