<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\KsrLauncher.Core\KsrLauncher.Core.csproj" />
    <None Include="..\..\src\KsrLauncher.App\ServerSettingsWindow.xaml" Link="ServerSettingsWindow.xaml" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\..\.github\workflows\release-launcher.yml" Link="release-launcher.yml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
